config/routes.rb
Spree::Core::Engine.routes.prepend do
  match 'product_customizations/price', :to => 'product_customizations#price'

  match 'customize/:product_id', :to => 'products#customize', :as => 'customize'

  namespace :admin do

    # resources :configuration_exclusions
    resources :product_customization_types do
      resources :customizable_product_options do
        member do
          get :select
          post :select
          get :remove
        end
        collection do
          get :available
          get :selected
        end
      end
    end

    resources :product_customization_types

    resources :ad_hoc_option_types do
      resources :ad_hoc_option_values do
        collection do
          post :update_positions
        end
      end
      member do
        get :remove
      end
    end

    delete '/ad_hoc_option_values/:id', :to => "ad_hoc_option_values#destroy", :as => :ad_hoc_option_value

    resources :ad_hoc_variant_exclusions

    resources :products do
      resources :option_types do
        member do
          get :select
          get :remove
          get :select_ad_hoc
          post :select_ad_hoc
        end
        collection do
          get :available
          get :selected
          get :available_ad_hoc
        end
      end
      resources :ad_hoc_option_types do
        collection do
          get :selected
        end
        member do
          get :add_option_value
        end
      end

      resources :ad_hoc_variant_exclusions

      resources :product_customization_types do
        member do
          get :select
          post :select
          get :remove
        end
        collection do
          get :available
          get :selected
        end
      end
    end #products

  end # namespace :admin

  match 'admin/variant_configurations/:variant_id', :to => 'admin/variant_configurations#configure'
end

app/controllers/spree/admin/product_customization_types_controller.rb
module Spree
  class Admin::ProductCustomizationTypesController < Admin::ResourceController
    before_filter :load_product, :only => [:selected, :available, :remove]
    before_filter :load_calculators, :only => [:new, :edit]

    def load_calculators
      @calculators = ProductCustomizationType.calculators.sort_by(&:name)
    end

    def edit
      @product_customization_type= ProductCustomizationType.find(params[:id])

      # Is this an edit immediately after create?  If so, need to create
      # calculator-appropriate default options
      if @product_customization_type.customizable_product_options.empty?
        if !@product_customization_type.calculator.nil?

          opts = @product_customization_type.calculator.create_options
          @product_customization_type.customizable_product_options.concat opts if opts

          # for each mandatory input type
          #        @product_customization_type.calculator.required_fields.each_pair do |key, val|
          #          cpo= CustomizableProductOption.create(:name=>key, :presentation=>key.titleize, :is_required => true,:data_type=>val)
          #          @product_customization_type.customizable_product_options << cpo
          #        end
        end
      end
    end

    def available
      set_available_product_customization_types
      render :layout => false
    end

    def selected
      @product_customization_types = @product.product_customization_types
    end

    def remove
      @product.product_customization_types.delete(@product_customization_type)
      @product.save
      flash.notice = I18n.t("notice_messages.product_customization_type_removed")
      redirect_to selected_admin_product_product_customization_types_url(@product)
    end


    # AJAX method for selecting an existing option type and associating with the current product
    def select
      @product = Product.find_by_param!(params[:product_id])

      @product.product_customization_types << ProductCustomizationType.find(params[:id])
      @product.save
      @product_customization_types = @product.product_customization_types
      set_available_product_customization_types
    end

    protected

    def location_after_save
      if params[:action] == "update"
        admin_product_customization_types_url
      else
        edit_admin_product_customization_type_url(@product_customization_type)
      end
    end


    private
    def load_product
      @product = Product.find_by_param!(params[:product_id])
    end

    def set_available_product_customization_types
      @available_product_customization_types = ProductCustomizationType.all
      selected_product_customization_types = []
      @product.product_customization_types.each do |pct|
        selected_product_customization_types << pct
      end
      @available_product_customization_types.delete_if {|pct| selected_product_customization_types.include? pct}
    end
  end
end

app/views/spree/admin/product_customization_types/_available.html.erb
<h4><%= t("add_product_customization_types") %></h4>
<table class="index">
  <tr>
    <th><%= t("name") %></th>
    <th><%= t("presentation") %></th>
    <th><%= t("description") %></th>
    <th>&nbsp;</th>
  </tr>
  <% @available_product_customization_types.each do |ct| %>
  <tr>
    <td><%=ct.name %></td>
    <td><%=ct.presentation %></td>
    <td><%=ct.description %></td>
    <td class="actions"><%= link_to icon('add') + ' ' + t("select"),
                            url_for(:controller => "admin/product_customization_types",
                                    :id => ct,
                                    :product_id => @product.permalink,
                                    :action => "select",
                                    :product_customization_type_id =>  ct),
                           :remote => true, :class => 'iconlink' %>
    </td>
  </tr>
  <% end %>
  <% if @available_product_customization_types.empty? %>
  <tr>
    <td colspan="3"><%= t('none_available') %></td>
  </tr>
  <% end %>
</table>

app/views/spree/admin/product_customization_types/_customizable_product_option_fields.html.erb
<tr class="customization_value type fields" id="<%= dom_id(f.object) %>">
  <td><%= f.text_field :name, :readonly => true, :disabled => true %></td>
  <td><%= f.text_field :presentation %></td>
  <td><%= f.text_area :description, {:style=>'height: auto;', :rows => 3, :cols => 25} %></td>
  <td class="actions"><%= link_to_remove_nested_fields t("remove"), f, :no_text => true, :nest => "product_customization_type" %></td>
</tr>

app/views/spree/admin/product_customization_types/_form.html.erb
<%= f.field_container :name do %>
  <%= f.label :name, t("name") %><br />
  <%= f.text_field :name %>
  <%= f.error_message_on :name %>
<% end %>

<%= f.field_container :presentation do %>
  <%= f.label :presentation, t("presentation") %><br />
  <%= f.text_field :presentation %>
  <%= f.error_message_on :presentation %>
<% end %>

<%= f.field_container :description do %>
  <%= f.label :description, t("description") %><br />
  <%= f.text_field :description %>
  <%= f.error_message_on :description %>
<% end %>

<%= render "spree/admin/shared/calculator_fields", :f => f %>

app/views/spree/admin/product_customization_types/_selected.html.erb
<table class="index">
  <tr>
    <th><%= t("name") %></th>
    <th><%= t("presentation") %></th>
    <th><%= t("description") %></th>
    <th>&nbsp;</th>
  </tr>
  <% @product_customization_types.each do |customization_type| %>
    <tr>
      <td><%= customization_type.name %></td>
      <td><%= customization_type.presentation %></td>
      <td><%= customization_type.description %></td>
      <td class="actions">
      <%= link_to_with_icon 'delete',  t("remove"), remove_admin_product_product_customization_type_url(@product, customization_type) %>
      </td>
    </tr>
  <% end %>
  <% if @product_customization_types.empty? %>
   <tr><td colspan="3"><%= t(:none) %></td></tr>
  <% end %>
</table>

<div id="customization-types"></div>
  <span id="new_ct_link">
    <%= link_to icon('add') + ' ' + t("add_product_customization_type"), available_admin_product_product_customization_types_url(@product), :remote => :true, :class => 'iconlink' %>
  </span>

app/views/spree/admin/product_customization_types/available.js.erb
$("#customization-types").html("<%= raw escape_javascript(render('available')) %>");
$("#new_ct_link").hide();

app/views/spree/admin/product_customization_types/edit.html.erb
<%= content_for :head do %>
  <%= javascript_include_tag 'jquery.validate.min' %>
  <%= javascript_tag do %>
    $(function () {
      $('form').validate();
    });
  <% end %>
<% end %>

<%= render :partial => 'spree/admin/shared/product_sub_menu' %>
<h1><%= t("editing_product_customization_type") %></h1>
<%= render 'spree/shared/error_messages', :target => @product_customization_type %>
<%= form_for(@product_customization_type, :url => admin_product_customization_type_url(@product_customization_type), :html => { :method => :put }) do |f| %>
<fieldset>
  <legend><%= t("editing_product_customization_type") %></legend>
  <%= render :partial => "form", :locals => { :f => f } %>
  <h3><%= t("customizable_product_options") %></h3>
  <table class="index">
    <thead>
      <tr>
        <th><%= t("name") %></th>
        <th><%= t("presentation") %></th>
        <th><%= t("description") %></th>
        <th></th>
      </tr>
    </thead>
    <tbody id="customizable_product_options">
      <tr id="none">
        <td colspan="3"><%= @product_customization_type.customizable_product_options.empty? ? t("none") : "" %></td>
      </tr>
      <%= f.fields_for :customizable_product_options do |customizable_form| %>
        <%= render "customizable_product_option_fields", :f => customizable_form %>
      <% end %>
    </tbody>
  </table>
  <%# link_to_add_fields t("add_customizable_product_option"), "tbody#customizable_product_options", f, :customizable_product_options %>

<!-- b/c of r_c removal -->
<p class="form-buttons">
  <%= button t("update") %>
  <%= t("or") %> <%= link_to t("cancel"), admin_product_customization_types_url %>
</p>

<!--   < %= # render :partial => 'admin/shared/edit_resource_links' % > -->
</fieldset>
<% end %>

app/views/spree/admin/product_customization_types/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<% content_for(:page_title, Spree.t("product_customization_types")) %>
<% content_for(:page_actions) do %>
  <li id="new_product_customization_type_link">
    <%= button_link_to Spree.t("new_product_customization_type"), new_admin_product_customization_type_url, {:icon => 'add', :id => 'new_product_customization_type_link'} %>
  </li>
<% end %>

<table class="index sortable" id='listing_product_customization_types'>
  <tr>
    <th><%= Spree.t("name") %></th>
    <th><%= Spree.t("presentation") %></th>
    <th><%= Spree.t("description") %></th>
    <th></th>
  </tr>
  <% @product_customization_types.each do |product_customization_type| %>
    <tr id="<%= dom_id product_customization_type %>">
      <td><span class="handle"></span> <%= product_customization_type.name %></td>
      <td class='presentation'><%= product_customization_type.presentation %></td>
      <td class='description'><%= product_customization_type.description %></td>
      <td class="actions">
        <%= link_to_edit(product_customization_type, :class => 'admin_edit_product_customization_type') %>
        &nbsp;
        <%= link_to_delete(product_customization_type) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/spree/admin/product_customization_types/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render 'spree/shared/error_messages', :target => @product_customization_type%>

<%= form_for(@product_customization_type, :url => admin_product_customization_types_url) do |f| %>
  <fieldset>
    <legend><%= t("new_product_customization_type") %></legend>
    <%= render :partial => "form", :locals => { :f => f } %>
<!--     < %= render :partial => 'spree/admin/shared/new_resource_links' % >

put this back in once r_c is removed
-->


<p class="form-buttons">
  <%= button t("actions.create") %>
  <%= t("or") %> <%= link_to t("actions.cancel"), admin_product_customization_types_url %>
</p>


  </fieldset>
<% end %>

app/views/spree/admin/product_customization_types/select.js.erb
$("#selected-customization-types").html("<%= raw escape_javascript(render 'selected') %>");
$("#customization-types").html("");
$("#new_ct_link").show();

app/views/spree/admin/product_customization_types/selected.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => "Product Customization Types"} %>

<div id="selected-customization-types">
  <%= render 'selected' %>
</div>